Lesson1
GlebMakhankov/webix-styling pull request #1
Opened 2021-09-30 17:44 UTC by GlebMakhankov

2021-09-30 18:20 UTC, AlexeyXB requested changes

2021-09-30 18:20 UTC, AlexeyXB commented on src/components/myCustomBtn.js
> +  {
Сделай тут рефакторинг, чтобы проще читалось

2021-09-30 18:22 UTC, AlexeyXB requested changes

2021-09-30 18:22 UTC, AlexeyXB commented on src/components/myCustomForm.js
> +export default webix.protoUI(
Тут тоже просится рефакторинг

2021-09-30 20:00 UTC, HelgaListopad approved these changes
Рефакторинг кода действительно не помешает ( на усмотрение @AlexeyXB ), но именно по заданию других замечаний у меня нет

2021-10-01 05:32 UTC, AlexeyXB approved these changes

2021-10-01 05:32 UTC, merged